version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/registration-processor" 
    schedule:
      interval: "daily"
    target-branch: "develop-java21"
    open-pull-requests-limit: 50
